server:
  port: 8088
spring:
  application:
    name: auth
config:
  jwt:
    # \u52A0\u5BC6\u5BC6\u94A5
    secret: abcdefg1234567
    # token\u6709\u6548\u65F6\u957F
    expire: 3600
    # header \u540D\u79F0
    header: token

